### ISSUE TITLE
Report zero division error

### ISSUE THREAD

**Issue by LeamHall** [LeamHall/bookbot#31]
Traceback (most recent call last):
  File "/usr/local/src/LeamHall/bookbot/bookbot.py", line 416, in <module>
    chapters, specials = parse_chapters(
                         ^^^^^^^^^^^^^^^
  File "/usr/local/src/LeamHall/bookbot/bookbot.py", line 408, in parse_chapters
    chapters.append(Chapter(data))
                    ^^^^^^^^^^^^^
  File "/usr/local/src/LeamHall/bookbot/bookbot.py", line 227, in __init__
    self.report = Report(data=self.lines, filename=self.filename)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/src/LeamHall/bookbot/bookbot.py", line 156, in __init__
    self._grade_report()
  File "/usr/local/src/LeamHall/bookbot/bookbot.py", line 199, in _grade_report
    self.sentence_average = self.word_count / self.sentence_count
                            ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero

**Comment by LeamHall** [comment]
Also, the "report" flag in book_config.toml isn't being respected.

**Comment by LeamHall** [comment]
This came back with an almost empty chapter, since the first line can be slurped as the header. I assume the book author can deal with empty chapters, so pass on the exceptions.
